[package.dependencies]
BepInEx-BepInExPack_V_Rising = "1.733.2"

[publish]
communities = ["v-rising"]
repository = "https://thunderstore.io"

[publish.categories]
v-rising = ["oakveil-update", "mods", "client"]

[package]
namespace = "DiNaSoR"
name = "BloodUI"
versionNumber = "1.4.0"
description = "Client UI companion for BloodCraft - HUD bars, character menu, and quest tracking!"
websiteUrl = "https://github.com/DiNaSoR/BloodUI"
containsNsfwContent = false

[build]
icon = "./icon.png"
readme = "./README.md"
changelog = "./CHANGELOG.md"
outdir = "./build"

[[build.copy]]
source = "./bin/Release/net6.0/BloodUI.dll"
target = "/BepInEx/plugins/"
